export const home = "/"
export const login = "/login"
export const register = "/register"
export const signOut = "/signOut"
export const registerSuccess = "/register/success"
export const videoCapture = "/video-capture"
